# Generated by Django 4.1.7 on 2023-03-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("album", models.CharField(max_length=100)),
                (
                    "length",
                    models.PositiveIntegerField(help_text="Length of song in seconds"),
                ),
                ("release_date", models.DateField(auto_now=True)),
                ("genre", models.CharField(max_length=100)),
            ],
        ),
    ]
