# Generated by Django 4.1.7 on 2023-03-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
