# Generated by Django 4.1.7 on 2023-04-04 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_music_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="release_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
